// Dati iniziali ricavati dai fogli di inventario manuale (currentStock al 19/05/2026,
// totale di Giacenza + Entrate - Uscite). Sono ammessi decimali (0,5 = mezza cassetta).
// L'admin puo' modificare/aggiungere prodotti, soglie, unita' e ordinamento dopo il primo avvio.

export const CATEGORIES = [
  { id: 'acque',         name: 'Acque',              icon: '💧', order: 1 },
  { id: 'birre',         name: 'Birre & Fusti',      icon: '🍺', order: 2 },
  { id: 'analcoliche',   name: 'Bevande',            icon: '🥤', order: 3 },
  { id: 'amari',         name: 'Amari & Distillati', icon: '🥃', order: 4 },
  { id: 'cocktail',      name: 'Cocktail Bar',       icon: '🍸', order: 5 },
  { id: 'vini-bianchi',  name: 'Vini Bianchi',       icon: '🥂', order: 6 },
  { id: 'vini-rossi',    name: 'Vini Rossi',         icon: '🍷', order: 7 },
];

export const UNITS = ['bottiglia', 'cassetta', 'fusto', 'bombola', 'lattina', 'kg', 'pz'];

const slug = (s) => s
  .toLowerCase()
  .normalize('NFD').replace(/[̀-ͯ]/g, '')
  .replace(/[^a-z0-9]+/g, '-')
  .replace(/(^-|-$)/g, '');

let _order = 0;
const p = (name, category, unit = 'bottiglia', minThreshold = 2, currentStock = 0) => ({
  id: slug(name),
  name,
  category,
  unit,
  currentStock,
  minThreshold,
  costPrice: 0,
  salePrice: 0,
  supplierId: null,
  archived: false,
  order: ++_order,
});

export const PRODUCTS = [
  // ===== Acque =====
  p('Acqua Naturale',     'acque',       'cassetta', 3, 10),
  p('Acqua Frizzante',    'acque',       'cassetta', 3, 24),
  p('Acqua Ferrarelle',   'acque',       'cassetta', 2, 11),

  // ===== Birre & Fusti =====
  p('Fusti Heineken',     'birre',       'fusto', 1, 0),
  p('Fusti Affligen',     'birre',       'fusto', 1, 5),
  p('Fusti Messina',      'birre',       'fusto', 1, 7),
  p('Bombola CO2',        'birre',       'bombola', 1, 1),
  p('Heineken 0',         'birre',       'cassetta', 2, 1.5),
  p('Heineken',           'birre',       'cassetta', 2, 4),
  p('Corona',             'birre',       'cassetta', 2, 1),
  p('Erdinger',           'birre',       'cassetta', 2, 1),
  p('Fisher',             'birre',       'cassetta', 2, 1),
  p('Blanche De Namur',   'birre',       'cassetta', 2, 2),

  // ===== Bevande analcoliche =====
  p('Coca Zero 33cl',     'analcoliche', 'cassetta', 2, 2.5),
  p('Coca Cola 33cl',     'analcoliche', 'cassetta', 2, 11),
  p('Coca Cola 1lt',      'analcoliche', 'cassetta', 2, 2),
  p('Chinotto',           'analcoliche', 'cassetta', 2, 3),
  p('Gazzosa',            'analcoliche', 'cassetta', 2, 2),
  p('Limonata',           'analcoliche', 'cassetta', 2, 0.5),
  p('Aranciata bio',      'analcoliche', 'cassetta', 2, 0.5),
  p('Acqua Tonica',       'analcoliche', 'cassetta', 2, 2),
  p('Schweppes Lemon',    'analcoliche', 'cassetta', 2, 0.5),
  p('Ginger Beer',        'analcoliche', 'cassetta', 2, 1.5),
  p('Succo Ananas',       'analcoliche', 'cassetta', 2, 1),
  p('Succo Arancia',      'analcoliche', 'cassetta', 2, 1),
  p('Succo Pesca',        'analcoliche', 'cassetta', 2, 2),

  // ===== Amari & Distillati =====
  p('Amaro Amara',                'amari', 'bottiglia', 2, 1),
  p('Amaretto Disaronno',         'amari', 'bottiglia', 2, 0),
  p('Amaro Unnimaffissu',         'amari', 'bottiglia', 2, 0),
  p('Amaro Montenegro',           'amari', 'bottiglia', 2, 2),
  p('Amaro Averna',               'amari', 'bottiglia', 2, 2),
  p('Amaro Del Capo',             'amari', 'bottiglia', 2, 2),
  p('Amaro Del Capo piccante',    'amari', 'bottiglia', 2, 1),
  p("Amaro Dell'Etna",            'amari', 'bottiglia', 2, 1),
  p('Amaro Unicum',               'amari', 'bottiglia', 2, 2),
  p('Branca Menta',               'amari', 'bottiglia', 2, 1),
  p('Fernet Branca',              'amari', 'bottiglia', 2, 1),
  p('Jefferson',                  'amari', 'bottiglia', 2, 2),
  p('Jagermeister',               'amari', 'bottiglia', 2, 1),
  p('Limoncello',                 'amari', 'bottiglia', 2, 2),
  p('Baileys',                    'amari', 'bottiglia', 2, 2),
  p('Jack Daniels',               'amari', 'bottiglia', 2, 2),
  p('Zacapa 23',                  'amari', 'bottiglia', 2, 0),
  p('Drambuie',                   'amari', 'bottiglia', 2, 2),
  p('Grand Marnier',              'amari', 'bottiglia', 2, 1),
  p('Matusalem',                  'amari', 'bottiglia', 2, 1),
  p('Ballantines',                'amari', 'bottiglia', 2, 1),
  p('Bushmills',                  'amari', 'bottiglia', 2, 1),
  p('Martell Cognac',             'amari', 'bottiglia', 2, 1),
  p('Prime uve',                  'amari', 'bottiglia', 2, 1),
  p('Pampero',                    'amari', 'bottiglia', 2, 1),
  p('Grappa Barricata 903',       'amari', 'bottiglia', 2, 2),
  p('Diciotto Lune',              'amari', 'bottiglia', 2, 1),
  p('Havana Club 7',              'amari', 'bottiglia', 2, 2),
  p('Havana Club 3',              'amari', 'bottiglia', 2, 1),
  p('Passito',                    'amari', 'bottiglia', 2, 1),
  p('Vino alle Mandorle',         'amari', 'bottiglia', 2, 1),
  p('Zibibbo',                    'amari', 'bottiglia', 2, 1),

  // ===== Cocktail Bar =====
  p('Aperol',                     'cocktail', 'bottiglia', 2, 0),
  p('Batida De Coco',             'cocktail', 'bottiglia', 2, 1),
  p('Campari',                    'cocktail', 'bottiglia', 2, 0),
  p('Cointreau',                  'cocktail', 'bottiglia', 2, 10),
  p('Gin Bombay',                 'cocktail', 'bottiglia', 2, 6),
  p('Gin Gordon',                 'cocktail', 'bottiglia', 2, 0),
  p("Gin Hendrick's",             'cocktail', 'bottiglia', 2, 1),
  p('Gin Tanqueray',              'cocktail', 'bottiglia', 2, 1),
  p('Gin Portofino',              'cocktail', 'bottiglia', 2, 7),
  p('Gin Etsu',                   'cocktail', 'bottiglia', 2, 1),
  p('Gin Panarea Island',         'cocktail', 'bottiglia', 2, 1),
  p('Gin Panarea Sunset',         'cocktail', 'bottiglia', 2, 1),
  p('Gin Etneum',                 'cocktail', 'bottiglia', 2, 1),
  p('Gin Legend',                 'cocktail', 'bottiglia', 2, 1),
  p('Gin Mare',                   'cocktail', 'bottiglia', 2, 10),
  p('Tequila Jose Cuervo',        'cocktail', 'bottiglia', 2, 2),
  p('Tequila Jose Cuervo Silver', 'cocktail', 'bottiglia', 2, 2),
  p('Triplesec',                  'cocktail', 'bottiglia', 2, 1),
  p('Kahlua',                     'cocktail', 'bottiglia', 2, 2),
  p('Curacao blu',                'cocktail', 'bottiglia', 2, 3),
  p('Martini Bianco',             'cocktail', 'bottiglia', 2, 1),
  p('Martini Rosso',              'cocktail', 'bottiglia', 2, 2),
  p('Martini Extra Dry',          'cocktail', 'bottiglia', 2, 3),
  p('Peachtree',                  'cocktail', 'bottiglia', 2, 1),
  p('Sambuca',                    'cocktail', 'bottiglia', 2, 1),
  p('St Germain',                 'cocktail', 'bottiglia', 2, 1),
  p('Tequila',                    'cocktail', 'bottiglia', 2, 1),
  p('Midori',                     'cocktail', 'bottiglia', 2, 0),
  p('Malibu',                     'cocktail', 'bottiglia', 2, 3),
  p('Passoa PassionFruit',        'cocktail', 'bottiglia', 2, 1),
  p('Vodka Raspberry',            'cocktail', 'bottiglia', 2, 1),
  p('Vodka Absolut',              'cocktail', 'bottiglia', 2, 0),
  p('Vodka Belvedere',            'cocktail', 'bottiglia', 2, 1),
  p('Vodka Grey Goose',           'cocktail', 'bottiglia', 2, 2),
  p('Vodka Sky',                  'cocktail', 'bottiglia', 2, 1),
  p('Vodka Beluga',               'cocktail', 'bottiglia', 2, 1),
  p('Vodka alla Pesca',           'cocktail', 'bottiglia', 2, 1),
  p('Vodka alla Fragola',         'cocktail', 'bottiglia', 2, 1),
  p('Vodka Moskowskai',           'cocktail', 'bottiglia', 2, 2),

  // ===== Vini Bianchi =====
  p('Carizza',                    'vini-bianchi', 'bottiglia', 2, 4),
  p('Cusinì',                     'vini-bianchi', 'bottiglia', 2, 0),
  p('Cisirì',                     'vini-bianchi', 'bottiglia', 2, 0),
  p('Tornatore Etna Bianco',      'vini-bianchi', 'bottiglia', 2, 0),
  p('Grillo Santa Tresa',         'vini-bianchi', 'bottiglia', 2, 0),
  p('Iancura',                    'vini-bianchi', 'bottiglia', 2, 1),
  p('Mango Tenuta San',           'vini-bianchi', 'bottiglia', 2, 0),
  p('Gulfi Caricanti',            'vini-bianchi', 'bottiglia', 2, 0),
  p('Borelli Prosecco',           'vini-bianchi', 'bottiglia', 2, 3),
  p('Carpenè Malvolti',           'vini-bianchi', 'bottiglia', 2, 0),
  p('Chardonnay Principi di',     'vini-bianchi', 'bottiglia', 2, 0),

  // ===== Vini Rossi =====
  p('Tornatore Etna Rosso',           'vini-rossi', 'bottiglia', 2, 3),
  p("Surya Nero d'Avola",             'vini-rossi', 'bottiglia', 2, 1),
  p('Sul Vulcano Etna Rosso',         'vini-rossi', 'bottiglia', 2, 0),
  p('Santa Tresa Frappato',           'vini-rossi', 'bottiglia', 2, 0),
  p('Santa Tresa Cerasuolo Vittoria', 'vini-rossi', 'bottiglia', 2, 2),
  p('Maria Costanza',                 'vini-rossi', 'bottiglia', 2, 0),
  p('Kayd Syrah',                     'vini-rossi', 'bottiglia', 2, 0),
  p('Graci Etna Rosso',               'vini-rossi', 'bottiglia', 2, 0),
  p('Cottanera Etna',                 'vini-rossi', 'bottiglia', 2, 0),
  p('Buttitah',                       'vini-rossi', 'bottiglia', 2, 0),
  p("Amorì Nero d'Avola",             'vini-rossi', 'bottiglia', 2, 6),
  p("L'amorì",                        'vini-rossi', 'bottiglia', 2, 0),
];
